#!/bin/sh

if [ "$1" = menu ]; then
	boot-menu-add-entry "$0" "kernel & rootfs on SD card"
	exit
fi

global.bootm.image="/boot/linuximage"
global.bootm.oftree="/boot/wpan-at86rf233-bone.dtb"
#global.bootm.oftree="/boot/wpan-mrf24j40ma-bone.dtb"
#global.bootm.initrd=<path to initrd>
global.linux.bootargs.dyn.root="root=/dev/mmcblk0p2 rootfstype=ext4 rootwait rw"

